### ISSUE TITLE
Implement rendering of paths and arcs

### ISSUE THREAD

**Issue by hgonomeg** [moorhen-coot/LhasaReact#3]
## Tasks
* [x] Paths
  * [x] Do the right thing in C++ first - https://github.com/hgonomeg/coot/issues/68
  * [x] Rewrite the whole handling of paths to adjust to the new design
 * [x] Arcs
   * [x] Fix up the existent implementation
